#!/bin/sh
if [ "$IFACE" = lo ]; then
/usr/bin/python3.7 /usr/local/auction_manager_app/auction_manager_app.py stop > /dev/null 2>&1
/usr/bin/python3.7 /usr/local/auction_manager_app/auction_manager_app.py start > /dev/null 2>>/usr/local/auction_manager_app/errors.log
/usr/bin/python3.7 /usr/local/auction_manager_app/start_and_restart_auction_manager_app.py stop > /dev/null 2>&1
/usr/bin/python3.7 /usr/local/auction_manager_app/start_and_restart_auction_manager_app.py start > /dev/null 2>>/usr/local/auction_manager_app/errors.log
fi